# Generated by Django 3.0.5 on 2021-08-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odata', '0004_auto_20210803_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
