# Generated by Django 3.0.5 on 2022-09-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odata', '0005_auto_20211219_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='wishlist',
            field=models.TextField(null=True),
        ),
    ]
