# Generated by Django 3.0.5 on 2022-01-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odata', '0005_auto_20211219_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
