# Generated by Django 3.0.5 on 2021-08-25 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odata', '0005_customer_father_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='father_name',
        ),
    ]
