# Generated by Django 3.0.5 on 2023-02-21 09:31

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('odata', '0006_auto_20220926_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.AddField(
            model_name='customer',
            name='checkout',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='checkout_quantity',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='discount',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='discount_value',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='dob',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='salutation_billing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='voucher',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='voucher_value',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color_de',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color_variant',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='ean',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size_variant',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='picture',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_card_type_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Discount %'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, max_length=100, null=True)),
                ('product_details', models.TextField(null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odata.Customer')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odata.Payment')),
            ],
        ),
    ]
